name: 'install-spatial-deps'
description: 'Action to install system dependencies of geospatial packages'
author: 'Alex Chubaty'
runs:
  using: "composite"
  steps:
      - name: Install geospatial system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update -y
          sudo apt-get install -y libudunits2-dev libgdal-dev libgeos-dev libproj-dev libsqlite0-dev
        shell: bash
      - name: Install geospatial system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install pkg-config
          brew install gdal
        shell: bash
