## Workflow derived from https://github.com/r-lib/actions/tree/v2/examples and
##   https://github.com/yihui/crandalf/blob/main/.github/workflows/rev-check.yaml
##
## Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: 'revdeps-check'
description: 'Action to run reverse dependency checks for R packages'
author: 'Alex Chubaty'
inputs:
  quiet:
    description: "Logical. Suppress output from internal processes?"
    required: true
    default: true
  timeout:
    description: "Integer. Maximum time to wait (in minutes) for R CMD check to complete per revdep."
    required: true
    default: 30
runs:
  using: "composite"
  steps:
      - name: Install additional package dependencies
        ## install pkgs separately; keep this order to avoid conflicts
        run: |
          pak::pkg_install("fs")
          pak::pkg_install("HenrikBengtsson/revdepcheck.extras")
          pak::pkg_install("r-lib/revdepcheck")
          pak::pkg_install("achubaty/crancache@r-universe")
        shell: Rscript {0}

      - name: Record crancache info
        id: crancache-info
        run: |
          echo "R_CRANCACHE=$(Rscript -e 'cat(crancache::get_cache_dir())')" >> "$GITHUB_OUTPUT"
          echo "R_VERSION=$(Rscript -e 'cat(as.character(getRversion()))')" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: Restore the crancache
        id: crancache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.crancache-info.outputs.R_CRANCACHE }}
          key: ${{ runner.os }}-R${{ steps.crancache-info.outputs.R_VERSION }}-crancache

      - name: Populate the crancache
        id: crancache-populate
        ## manual pre-installation uses crancache:
        ##  - sequentially install deps of each revdeps package in parallel;
        ##  - NOTE: PE pkgs aren't crancached, and will be installed each time.
        run: |
          options(revdepcheck.num_workers = getOption("Ncpus", 2L))

          omit_pkgs <- c(
            "SpaDES.project" ## omit b/c it circularly Suggests SpaDES.config
          )
          revdeps <- c(
            revdepcheck.extras::revdep_children(),
            revdepcheck.extras::revdep_grandchildren()
          ) |>
            setdiff(omit_pkgs)

          crancache::update_packages(lib.loc = .libPaths()[1], ask = FALSE)
          revdepcheck.extras::revdep_precache(pkgs = revdeps)

          if (Sys.info()[["sysname"]] == "Darwin") {
            fs::path("revdep", "library.noindex", revdeps) |> fs::dir_create()
          } else {
            fs::path("revdep", "library", revdeps) |> fs::dir_create()
          }
          lapply(revdeps, revdepcheck:::deps_install, pkgdir = ".")
        shell: Rscript {0}

      - name: Check reverse dependencies
        id: revdeps-check
        run: |
          options(revdepcheck.num_workers = getOption("Ncpus", 2L))

          omit_pkgs <- c(
            "SpaDES.project" ## omit b/c it circularly Suggests SpaDES.config
          )
          revdeps <- c(
            revdepcheck.extras::revdep_children(),
            revdepcheck.extras::revdep_grandchildren()
          ) |>
            setdiff(omit_pkgs)

          ## setup revdeps checks
          revdepcheck.extras::revdep_init()
          revdepcheck::revdep_add(packages = revdeps)

          ## run revdeps checks
          revdepcheck::revdep_check(
            num_workers = getOption("revdepcheck.num_workers", 2L),
            quiet = as.logical("${{ inputs.quiet }}"),
            timeout = as.difftime("${{ inputs.timeout }}", units = "mins")
          )

          ## save revdeps check reports
          revdepcheck::revdep_report(all = TRUE)
        shell: Rscript {0}

      - name: Report issues with reverse dependencies
        id: revdeps-report
        run: |
          echo "$(Rscript -e 'revdepcheck::revdep_report_summary()')" >> "$GITHUB_STEP_SUMMARY"

          echo "::group::Reverse dependency failures"
          echo "$(cat revdep/failures.md)"
          echo "::endgroup::"

          echo "::group::Reverse dependency problems"
          echo "$(cat revdep/problems.md)"
          echo "::endgroup::"
        shell: bash

      - name: Upload check results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ runner.os }}-revdeps-check-results
          if-no-files-found: ignore
          path: |
            00check_diffs.html
            latex.txt
            recheck
            recheck2
            *.Rcheck
            *.Rcheck2

      - name: Save crancache
        id: crancache-save
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.crancache-info.outputs.R_CRANCACHE }}
          key: ${{ steps.crancache-restore.outputs.cache-primary-key }}
