## Workflow derived from https://github.com/r-lib/actions/tree/v2/examples and
##   https://github.com/yihui/crandalf/blob/main/.github/workflows/rev-check.yaml
##
## Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: 'revdeps-check'
description: 'Action to run reverse dependency checks for R packages'
author: 'Alex Chubaty'
inputs:
  quiet:
    description: "Logical. Suppress output from internal processes?"
    required: true
    default: true
  timeout:
    description: "Integer. Maximum time to wait (in minutes) for R CMD check to complete per revdep."
    required: true
    default: 30
runs:
  using: "composite"
  steps:
      - name: Install additional package dependencies
        run: |
          ## install separately; keep this order to avoid conflicts
          pak::pkg_install("fs")
          pak::pkg_install("HenrikBengtsson/revdepcheck.extras")
          pak::pkg_install("r-lib/revdepcheck")
          pak::pkg_install("achubaty/crancache@r-universe")
        shell: Rscript {0}

      - name: Record crancache info
        id: crancache-info
        run: |
          echo "R_CRANCACHE=$(Rscript -e 'cat(crancache::get_cache_dir())')" >> "$GITHUB_OUTPUT"
          echo "R_VERSION=$(Rscript -e 'cat(as.character(getRversion()))')" >> "$GITHUB_OUTPUT"

      - name: Restore the crancache
        id: crancache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ steps.crancache-info.outputs.R_CRANCACHE }}
          key: ${{ runner.os }}-R${{ steps.crancache-info.outputs.R_VERSION }}-crancache

      - name: Populate the crancache
        id: crancache-populate
        run: |
          Rscript setup.R

      - name: Check reverse dependencies
        id: revdeps-check
        run: |
          echo "::group::Check reverse dependencies"
          Rscript check.R
          echo "::endgroup::"
          echo "$(Rscript -e 'revdepcheck::revdep_report_summary()')" >> "$GITHUB_STEP_SUMMARY"

      - name: Report issues with reverse dependencies
        id: revdeps-report
        run: |
          echo "::group::Reverse dependency failures"
          echo "$(cat revdep/failures.md)"
          echo "::endgroup::"
          echo "::group::Reverse dependency problems"
          echo "$(cat revdep/problems.md)"
          echo "::endgroup::"

      - name: Upload check results
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: ${{ runner.os }}-revdeps-check-results
          if-no-files-found: ignore
          path: |
            00check_diffs.html
            latex.txt
            recheck
            recheck2
            *.Rcheck
            *.Rcheck2

      - name: Save crancache
        id: crancache-save
        uses: actions/cache/save@v4
        with:
          path: ${{ steps.crancache-info.outputs.R_CRANCACHE }}
          key: ${{ steps.crancache-restore.outputs.cache-primary-key }}
