name: 'install-Require'
description: 'Action to install remotes and Require R packages'
author: 'Ceres Barros'
inputs:
  GitTag:
    description: "A character indicating the branch, commit SHA or tag to append to 'PredictiveEcology/Require@'. Defaults to 'master' branch"
    required: true
    default: "master"
runs:
  using: "composite"
  steps:
      - name: Install remotes
        run: |
          ## Installing remotes
          cat("::group::Installing remotes\n")
          cat("os-version=", sessionInfo()$running, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
          cat("r-version=", if (grepl("development", rv <- R.Version()$version.string)) as.character(getRversion()) else rv, "\n", file = Sys.getenv("GITHUB_OUTPUT"), sep = "", append = TRUE)
          install.packages("remotes")
          cat("::endgroup::\n")
        shell: Rscript {0}

      - name: Install Require
        run: |
          ## Installing Require
          cat("::group::Installing/updating Require\n")
          RequirePath <- paste0("PredictiveEcology/Require@", "${{ inputs.GitTag }}")
          remotes::install_github(RequirePath)
          cat("::endgroup::\n")
        shell: Rscript {0}
