name: 'install-SpaDES'
description: 'Action to install SpaDES packages'
author: 'Ceres Barros'
inputs:
  upgrade:
    description: "A boolean passed to 'Require::Require(..., upgrade)'"
    required: true
    default: true
runs:
  using: "composite"
  steps:
      - name: Install SpaDES packages
        run: |
          cat("::group::Installing SpaDES metapackage \n")
          Require::setLinuxBinaryRepo()
          Require::Require("SpaDES", require = FALSE, upgrade = as.logical("${{ inputs.upgrade }}"))
          cat("::endgroup::\n")
          cat("::group::Installing additional SpaDES packages from GitHub \n")
          Require::Require("PredictiveEcology/SpaDES.experiment@development",
            require = FALSE, upgrade = as.logical("${{ inputs.upgrade }}"))
          cat("::endgroup::\n")
        shell: Rscript {0}
